### ISSUE TITLE
[API] APIs with different definitions of test results and swagger

### ISSUE THREAD

**Issue by monstar-hashimoto-ryosuke** [mamori-i-japan/mamori-i-japan-api#138]
# APIs with different definitions of test results and swagger
The following is a summary of the [results](https://docs.google.com/spreadsheets/d/1O6B6yIB5Ze5hBKTQpb3OtcijqJB54UH1LWSU_A4XLGU/edit#gid=37216483) of the API unit test and the API with different definitions in swagger.
I think it's probably an omission in swagger, so please fix the definition.

- /admins/users/（GET）
  - Success
    - accessControlList(l.5)（#/components/schemas/Admin）
- /admins/users/{userId}（GET）
  - Success
    - accessControlList(l.28)（#/components/schemas/Admin）
  - Client Error
    - 404
      - usecase : invalid userId (l.30)
- /admins/users/{userId}（DELETE）
  - Client Error
    - 404
      - usecase : invalid userId (l.34)
- /admins/prefectures/（GET）
  - Success
    - accessControlList(l.59)（#/components/schemas/Prefecture）
- /admins/prefectures/{prefectureId}（GET）
  - Success
    - accessControlList(l.63)（#/components/schemas/Prefecture）
  - Client Error
    - 404
      - usecase : invalid prefectureId (l.64)
- /admins/prefectures/{prefectureId}（PATCH）
  - Client Error
    - 404
      - usecase : invalid prefectureId (l.68)

**Comment by yashmurty** [comment]
@monstar-hashimoto-ryosuke Is this still open?
Can you please check?

**Comment by monstar-hashimoto-ryosuke** [comment]
I've checked and it's OK, so I'm closing this issue.
